### ISSUE TITLE
Running any Mojo HTML app on a browser that does not support sound makes the whole application crash

### ISSUE THREAD

**Issue by ziggybcn** [blitz-research/monkey#12]
This is the detailed crash:

Monkey Runtime Error : ReferenceError: Audio is not defined
C:/Monkey_Compiler/MonkeyPro70b/modules/mojo/audio.monkey<43>

The expected behavior is that the app just ignores sound commands and does not crash.

**Comment by blitz-research** [comment]
What browser? So I can test...

**Comment by ziggybcn** [comment]
The easiest way to see this is using a browser that does not support html5 sound. the chrominium embeded framework browser is a good example. you can get it here: http://www.magpcss.net/cef_downloads/index.php?file=cef_binary_3.1364.1094_windows.zip
I managed to make it fail also using the Dolphin browser on my old Samsung Gallaxy Spica
The thing is that it would be nice if the audio part plays a bit nicer in case it fails to initialize. An exception instead of an error would be much better in my honest opinion, as it's not a bug on the code you can workaraound in any way

**Comment by blitz-research** [comment]
Do you know of a PC browser that doesn't support Audio? I don't really want
to have to build a c++ plugin or run Dolphin on your old Spica just to test
this!

**Comment by ziggybcn** [comment]
Of course, just try the browser in Ted or the one in Jungle Ide. Both show the issue.

**Comment by blitz-research** [comment]
Having trouble reproducing this - I have tried a munged Ted with both Qt 4.8 and Qt 5 and the mak/audiotest sample works OK. Note: you still need to use mserver - or some server of some kind.

Also, there is already code in Mojo to deal with the lack of in-browser audio objects, as IE used to have this problem. However, it may well have been damaged in the recent target refactoring. But it looks OK to me...

**Comment by blitz-research** [comment]
Some other thoughts: I'm on the Mac right now, and using Qt 4.8.4 - it may be there are problems with earlier versions and I'll try again on the PC at work Monday, but it'd really help if you can find a standalone browser (or perhaps send me a version of Jungle?) with the same problem.

Html5 apps running in Ted is pretty neat though...!

**Comment by blitz-research** [comment]
Fixed.
