### ISSUE TITLE
New targets and mojo

### ISSUE THREAD

**Issue by devolonter** [blitz-research/monkey#3]
Whether users can create new targets and native mojo files? For example, http://www.monkeycoder.co.nz/Community/posts.php?topic=4780. In this case, I think, Stage3D mojo version will be based on original mojo. Whether the author will be able to publish the source files openly? Would not that be a license violation?

**Comment by blitz-research** [comment]
Users can create/redistribute new mojo native files...I couldn't really stop them legally even if I wanted to.

**Comment by devolonter** [comment]
Thanks for answers, Mark!
