### ISSUE TITLE
Add keys like MODULENAME_IMPLEMENTED=False into all the remaining modules

### ISSUE THREAD

**Issue by aglitchman** [blitz-research/monkey#34]
Please add keys like MODULENAME_IMPLEMENTED=False into all the remaining Monkey modules:
- brl/httprequest.monkey
- brl/filesystem.monkey
- brl/process.monkey
- brl/monkeystore.monkey (prints "Invalid target" on any target <> ios/android)
- os/os.monkey

This shall allow to create new targets without having to change the Monkey source code. 

_I'm currently working on the Java_Tool target and users will not be able to install it without modifying by hand some of previously listed Monkey modules._

**Comment by blitz-research** [comment]
Will do, I'm actually in the process of cleaning up the preprocessor a bit
to make this easier.
