### ISSUE TITLE
Mojo natives for desktop not yet in develop branch

### ISSUE THREAD

**Issue by nobuyukinyuu** [blitz-research/monkey#43]
This one's probably an easy fix.  The free version of Monkey now includes desktop targets, but the develop branch hasn't yet reflected this by including native mojo files for those targets.

(Perhaps they're still covered by the original copyright license?)

**Comment by blitz-research** [comment]
There is no new code - 'glfw' has simply been renamed to 'desktop'! See: targets/glfw/TARGET.MONKEY

This only affects the name displayed in the IDE, nothing else, eg: Monkey code should still use #If TARGET="glfw" etc.

**Comment by blitz-research** [comment]
Aha, see what you mean now - will add.

**Comment by nobuyukinyuu** [comment]
Hey!  Looks like this one should be closed finally, I see it in today's commit :+1:
