### ISSUE TITLE
GLFW3+ANGLE Target doesn't have the 'PathToFilePath' changes from V85C

### ISSUE THREAD

**Issue by ImmutableOctet** [blitz-research/monkey#82]
As the title states, you forgot to change the ANGLE target's 'PathToFilePath' method. [This is the commit in question](https://github.com/blitz-research/monkey/commit/b674b5aa10d20773bd332ab15ac47d3e93ecdf35).

**Comment by blitz-research** [comment]
Thanks - most obvious screw-up I could make!
